# Generated by Django 4.1.1 on 2022-09-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_alter_destination_offer_alter_destination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='descr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
