# Generated by Django 4.1.1 on 2022-09-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_alter_destination_descr_alter_destination_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='static/img/place'),
        ),
    ]
